import "./globals.css";
import WalletProvider from "./provider/WalletProvider";

export const metadata = {
  title: "web3 Dino",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <WalletProvider>{children}</WalletProvider>
      </body>
    </html>
  );
}
